In [2]:
import numpy as np
from util import data
from key_preprocessing import get_key_down, extract_key_pressed

### Dino: Button Intervals

In [65]:
print('id', 'len', 'mean', 'std')
subjects = ['S201','S202','S203','S204','S205','S206','S207','S208','S209','S210',
'S211','S212','S213','S214','S215','S216','S217','S218','S219','S220',]
button_intervals = np.array([])
n_button_inputs = []

for s in subjects:
    file_name = s +  '_space'
    merged_data = data.load(file_name)
    button_input = np.unique(merged_data[:,1])
    n_button_inputs.append(len(button_interval))
    button_interval = button_input[1:] - button_input[:-1]
    print(s, len(button_input), button_interval.mean(), button_interval.std())
    button_intervals = np.concatenate((button_intervals, button_interval))

id len mean std
S201 551 1.165666752728549 0.5482620863773333
S202 586 1.027265134632078 0.5729237726700143
S203 479 1.2776136966928777 0.7981666704024082
S204 501 1.2152327575683595 0.6665132915591707
S205 539 1.1314746766285382 0.6017828159528881
S206 552 1.1923468264391115 0.6387072165573212
S207 528 1.1785889056421095 0.5740561556639121
S208 505 1.1881951557265387 0.6878242939587553
S209 634 1.0881780813467257 0.4809721863551856
S210 537 1.2071837876270066 0.621864490357509
S211 887 1.0355291380031921 0.5246245773841184
S212 593 1.1608955594333443 0.6097396828948091
S213 607 1.1278055359428079 0.531807562354087
S214 517 1.1759689889212912 0.6085929027144924
S215 546 1.1994504543619418 0.877681620952186
S216 584 1.1048596600521081 0.5566699308364241
S217 683 1.0867787763869659 0.5533813743221693
S218 643 1.036267243441763 0.39325830968989595
S219 809 1.0417908326824112 0.4654248984459549
S220 578 1.163170845917647 0.592555692061878


In [66]:
print("average n_button inputs : ", np.array(n_button_inputs).mean(), np.array(n_button_inputs).std())
print("button intervals statistics:", button_intervals.mean(), button_intervals.std())

average n_button inputs :  565.75 153.84241125255414
button intervals statistics: 1.1313564536720326 0.598363668868942


### Tabsonic: Button Intervals

In [67]:

pid, sound, key = 'S201', 'O', 'all'
file_name = '{}_{}_{}'.format(pid, sound, key)
musics = ['A', 'B', 'C', 'D', 'E']

button_intervals = np.array([])
n_button_inputs = []

sound = 'O'
for s in subjects:
    _n_button_inputs = []
    for music in musics:
        name = '{}_{}{}_{}'.format(s, music, sound, key)
        d = data.load(name)
        button_input = np.unique(d[:,1])
        _n_button_inputs.append(len(button_input))
        button_interval = button_input[1:] - button_input[:-1]
        button_intervals = np.concatenate((button_intervals, button_interval))
    n_button_inputs.append(_n_button_inputs)


In [68]:
n_button_inputs_per_participants = np.array(n_button_inputs).sum(axis=1)
n_button_inputs_per_participants

array([1456, 1544, 1452, 1479, 1709, 1459, 1464, 1435, 1486, 1481, 1590,
       1468, 1518, 1456, 1459, 1525, 1466, 1466, 1498, 1499])

In [69]:
print("average n_button inputs : ", n_button_inputs_per_participants.mean(), n_button_inputs_per_participants.std())
print("button intervals statistics:", button_intervals.mean(), button_intervals.std())

average n_button inputs :  1495.5 60.68731333647915
button intervals statistics: 0.46058345182515437 0.43147459706971425


In [74]:
def extract_key_pressed(key_inputs:np.array, key:str):
    return np.asarray([(key in key_input.split('/')) for key_input in key_inputs])

In [71]:
n_button_inputs_per_participants = np.array(n_button_inputs).sum(axis=1)
n_button_inputs_per_participants

array([1448, 1515, 1448, 1465, 1654, 1437, 1440, 1471, 1491, 1473, 1545,
       1471, 1473, 1463, 1461, 1494, 1478, 1504, 1518, 1452])

In [72]:
print("average n_button inputs : ", np.array(n_button_inputs_per_participants).mean(), np.array(n_button_inputs_per_participants).std())
print("button intervals statistics:", button_intervals.mean(), button_intervals.std())

average n_button inputs :  1485.05 47.419906157646494
button intervals statistics: 0.4608765389523729 0.4039370955125257


#### For each buttons

In [80]:
PID = ["".join(['S', str(200+i)]) for i in range(1, 21)]
MUSIC = ['A', 'B', 'C', 'D', 'E']
SOUND = ['O', 'X']
KEY = ['s', 'd', 'f', 'j', 'k', 'l']

sdfjkl = {'O':[], 'X':[]}
for sound in SOUND:
    for pid in PID:
        _sdfjkl = [0,0,0,0,0,0]
        for music in MUSIC:        
            data = np.loadtxt('rawdata/tabsonic/{}_{}{}.csv'.format(pid, music, sound), delimiter=',', dtype=str)
            key_inputs = data[:,3] #get raw data
            # new_key_inputs = np.zeros(len(key_inputs)) # create an empty column

            for i, k in enumerate(KEY):
                # 1. for each key, extract timing at which the target key is down
                # 2. update 'new key inputs' after encoding
                target_key = extract_key_pressed(key_inputs, k)
                target_key_down = get_key_down(target_key)
                _sdfjkl[i] += len(target_key_down[target_key_down])
        sdfjkl[sound].append(_sdfjkl)   

In [83]:
sound_o = np.array(sdfjkl['O'])
print('mean', np.mean(sound_o, axis=0))
print('std', np.std(sound_o, axis=0))

mean [ 15.45 580.05 179.3  201.25 571.4   15.1 ]
std [10.00737228 16.14767785 11.56330403 11.01759956 17.19418506  9.15368778]


In [85]:
sound_x = np.array(sdfjkl['X'])
print('mean', np.mean(sound_x, axis=0))
print('std', np.std(sound_x, axis=0))

mean [ 13.2  574.4  179.15 200.   566.55  14.45]
std [ 8.48292402 13.61396342 10.87784446  9.72625313 14.43078307  8.3933009 ]


### Expanding Target : Button Inputs

In [60]:
P = ['S101','S102','S103','S104','S105','S106','S107','S108','S109','S110','S111','S112']
button_intervals = np.array([])
n_button_inputs = []
for cond in ['10', '11', '12', '20', '21', '22', '30', '31', '32', '40', '41', '42', '20']:
    _n_button_inputs = []
    for p in P:
        if easing == '' and duration == '':
            name = p
        else:
            name = 'et32/{}_{}'.format(p, cond)
        d = data.load(name)
        button_input = np.unique(d[:,1])
        _n_button_inputs.append(len(button_input))
        button_interval = button_input[1:] - button_input[:-1]
        button_intervals = np.concatenate((button_intervals, button_interval))
        if type(merged_data) != type(None):
            merged_data = np.vstack([merged_data, d])
        else:
            merged_data = d
    n_button_inputs.append(_n_button_inputs)

In [61]:
n_button_inputs

[[59, 55, 52, 57, 61, 54, 54, 57, 57, 60, 54, 59],
 [55, 55, 51, 54, 53, 56, 58, 56, 52, 58, 60, 55],
 [52, 55, 52, 56, 55, 54, 56, 55, 58, 56, 56, 58],
 [55, 51, 55, 52, 55, 57, 54, 57, 58, 60, 56, 54],
 [57, 55, 55, 59, 56, 56, 57, 55, 57, 53, 57, 57],
 [53, 57, 49, 57, 58, 55, 58, 55, 59, 54, 59, 54],
 [58, 52, 53, 57, 60, 57, 57, 54, 54, 55, 54, 57],
 [55, 52, 52, 55, 60, 51, 55, 56, 54, 61, 57, 56],
 [58, 51, 54, 52, 58, 54, 58, 54, 56, 56, 56, 53],
 [52, 56, 56, 54, 53, 53, 58, 55, 55, 57, 58, 53],
 [56, 57, 56, 57, 54, 56, 56, 50, 55, 53, 56, 56],
 [55, 56, 56, 58, 56, 54, 56, 59, 57, 55, 56, 57],
 [55, 51, 55, 52, 55, 57, 54, 57, 58, 60, 56, 54]]

In [62]:
n_button_inputs_per_participants = np.array(n_button_inputs).mean(axis=1)
n_button_inputs_per_participants

array([56.58333333, 55.25      , 55.25      , 55.33333333, 56.16666667,
       55.66666667, 55.66666667, 55.33333333, 55.        , 55.        ,
       55.16666667, 56.25      , 55.33333333])

In [63]:
print("average n_button inputs : ", np.array(n_button_inputs_per_participants).mean(), np.array(n_button_inputs_per_participants).std())
print("button intervals statistics:", button_intervals.mean(), button_intervals.std())

average n_button inputs :  55.53846153846154 0.4832840211530965
button intervals statistics: 2.859256560470669 0.9880206002436713
